// cspell:words nccmath CISA ISACA SCWCD
// cspell:ignore

= React v18
:toc:
:toclevels: 2
:toc-title: Contents
:sectnums:
:sectnumlevels: 5
:sectanchors:
:max-width: 1200px
:table-frame: ends
:table-stripes: none
:imagesdir: ./
:imagesoutdir: ./resources
:docinfo: shared-head
:docinfodir: ../
:source-highlighter: highlight.js
:source-indent: 2
:highlightjs-theme: github
//:prewrap!:
:icons: font
:iconfont-name: font-awesome
:iconfont-remote:
:iconfont-cdn: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css
:stem: latexmath

// https://github.com/asciidoctor/asciidoctor-kroki
:kroki-fetch-diagram: true
:kroki-default-format: svg
:kroki-default-options: inline
:kroki-server-url: https://kroki.io
// :plantuml-server-url: "http://plantuml.com/plantuml"


== Concepts

=== JSX

* React JSX is an extension to JavaScript. It allows writing a JavaScript code that looks like an HTML code.
* JSX supports expression in pure JavaScript syntax. Expression has to be enclosed inside the curly braces, `{` `}`. Expression can contain all variables available in the context, where the JSX is defined.
* It's important to distinguish between setting native HTML attributes, and setting custom React component props.
* Event handlers must be camelCased : `onClick`, `onKeyDown`
* JSX supports expression to be specified inside the attributes. In attributes, **double quote should not be used** along with expression.

[source, javascript]
....
const element = <h1>Hello React!</h1>

<script type="text/babel">
  var cTime = new Date().toTimeString();
  ReactDOM.render(
    <div><p>The current time is {cTime}</p></div>,
    document.getElementById('react-app') );
</script>
....

[source, html]
----
<style>
   .red { color: red }
</style>

<script type="text/babel">
   function getCurrentTime() {
      return new Date().toTimeString();
   }
   var class_name = "red";
   ReactDOM.render(
      <div>
         <p>The current time is <span className={class_name}>{getCurrentTime()}</span></p>
      </div>,
      document.getElementById('react-app')
   );
</script>
----

=== Component

* React component is the building block of a React application.
* The primary job of a React component is to render its user interface and update it whenever its internal state is changed.
** Initial rendering
** Event handling
** User interface updating

// https://github.com/asciidoctor/asciidoctor-kroki?tab=readme-ov-file#usage
[plantuml,align=center,opts=inline]
....
@startuml

class Component
class FunctionComponent
class ClassComponent{
  render()
}
class NestedComponent

Component <|-- FunctionComponent
Component <|-- ClassComponent


@enduml
....

* Note that an element in React is not a component, but a component is comprised of multiple elements.
* Function components are very minimal in nature. Its only requirement is to return a React element.

[source, javascript]
----
// function component
function Hello(){
  return '<div>Hello</div>';
}

// class component
class HelloComponent extends React.Component{
  render(){
    return ( <div>Hello</div> );
  }
}
----

=== PropTypes

* React community provides a special package, `prop-types` to address the properties type mismatch problem.
* `prop-types` allows the properties of the component to be specified with type through a custom setting (propTypes) inside the component.

* Typescript : compile-time type checking
* prop-types : runtime type checking

[source, javascript]
----
import React from 'react';
import PropTypes from 'prop-types';

class FormattedMoney extends React.Component{

  constructor(props){
    super(props);

  }

  format(amount){
    return parseFloat(amount).toFixed(2);
  }

  render(){
    return(
      <span>{this.format(this.props.value)}</span>
    )
  }
}

FormattedMoney.PropTypes = {
  value: PropTypes.number.isRequired
}
----

* https://hygraph.com/blog/react-proptypes[*How to use PropTypes in React*^]




=== Misc

* React toolchain will pre-process the css files ending with .module.css through CSS Module. Otherwise, it will be considered as a normal stylesheet.
* In short, the Props passed to a component are Read-Only.
* The concept of state allows React components to change their result as a response to changing user actions, network responses, etc. without violating this rule.

== API

[.ml-8, cols="*", options="header,autowidth"]
|===
^| Class or ^| Description ^| Members ^| Remarks

| https://legacy.reactjs.org/docs/react-api.html[`React`^]
| the entry point to the React library
|   | global

| https://legacy.reactjs.org/docs/react-component.html[`React.Component`^]
|   | `render()`, `constructor(__props__)` |

| https://legacy.reactjs.org/docs/react-dom.html[`ReactDOM`]
|   |   |
|===

=== Packages

[.ml-8, cols="*", options="header,autowidth"]
|===
^| Package ^| Description ^| Elements ^| Remarks

| https://www.npmjs.com/package/react[`react`^]
| a JavaScript library for creating user interfaces.
|   | facebook

| https://www.npmjs.com/package/react-dom[`react-dom`^]
| the entry point to the DOM and server renderers for React.
|   | facebook

| https://github.com/facebook/prop-types[`prop-types`^]
| Runtime type checking for React props and similar objects.
|   | facebook, MIT

| https://www.npmjs.com/package/react-error-boundary[`react-error-boundary`^]
| Reusable React error boundary component. |   |

| https://www.npmjs.com/package/@types/react[`@types/react`^]
| type definitions for react |   |

| https://www.npmjs.com/package/@types/react-dom[`@types/react-dom`^]
| type definitions for react-dom |   |

| https://www.npmjs.com/package/@types/prop-types[`@types/prop-types`^]
| type definitions for prop-types |   |

|===

== Guides

* https://wormwlrm.github.io/2021/11/07/Rollup-React-TypeScript.html[Rollup 기반 라이브러리 개발 환경 구성하기^]
* https://suzzeong.tistory.com/115[날짜 라이브러리 비교(Day.js, Moment.js, date-fns, Luxon)^]