// cspell:words nccmath CISA ISACA SCWCD
// cspell:ignore

= React v18
:toc:
:toclevels: 2
:toc-title: Contents
:sectnums:
:sectnumlevels: 5
:sectanchors:
:max-width: 1200px
:table-frame: ends
:table-stripes: none
:imagesdir: ./
// https://docs.asciidoctor.org/diagram-extension/latest/output/
:imagesoutdir: ./resources
:diagram-cachedir: ./cache
:docinfo: shared-head
:docinfodir: ../
:source-highlighter: highlight.js
:source-indent: 2
:highlightjs-theme: github
//:!prewrap:
:icons: font
:iconfont-name: font-awesome
:iconfont-remote:
:iconfont-cdn: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css
:stem: latexmath

// https://github.com/asciidoctor/asciidoctor-kroki
// :kroki-fetch-diagram: false
:kroki-default-format: svg
:kroki-default-options: inline
:kroki-server-url: https://kroki.io
:plantuml-server-url: "http://plantuml.com/plantuml"

[pass]
++++
<style type="text/tailwindcss">
  /*
  https://www.w3.org/TR/selectors-3/#selectors (CSS3 Selectors)
  https://tailwindcss.com/docs
  */

  h3 { margin-top: 1em; }
  h4 { margin-top: 2em; }

  .listingblock pre.highlightjs { @apply text-lg border-1 border-dotted ml-4 }
</style>
++++

== Concepts

=== JSX

* React JSX is an extension to JavaScript. It allows writing a JavaScript code that looks like an HTML code.
* JSX supports expression in pure JavaScript syntax. Expression has to be enclosed inside the curly braces, `{` `}`. Expression can contain all variables available in the context, where the JSX is defined.
* It's important to distinguish between setting native HTML attributes, and setting custom React component props.
* Event handlers must be camelCased : `onClick`, `onKeyDown`
* JSX supports expression to be specified inside the attributes. In attributes, **double quote should not be used** along with expression.

[source, javascript]
----
const element = <h1>Hello React!</h1>

<script type="text/babel">
  var cTime = new Date().toTimeString();
  ReactDOM.render(
    <div><p>The current time is {cTime}</p></div>,
    document.getElementById('react-app') );
</script>
----

[source, html]
----
<style>
   .red { color: red }
</style>

<script type="text/babel">
   function getCurrentTime() {
      return new Date().toTimeString();
   }
   var class_name = "red";
   ReactDOM.render(
      <div>
         <p>The current time is <span className={class_name}>{getCurrentTime()}</span></p>
      </div>,
      document.getElementById('react-app')
   );
</script>
----

=== Component

* React component is the building block of a React application.
* The primary job of a React component is to render its user interface and update it whenever its internal state is changed.
** Initial rendering
** Event handling
** User interface updating

// https://github.com/asciidoctor/asciidoctor-kroki?tab=readme-ov-file#usage
[plantuml,align=center,opts=inline]
....
@startuml

class Component
class FunctionComponent
class ClassComponent{
  render()
}
class NestedComponent

Component <|-- FunctionComponent
Component <|-- ClassComponent


@enduml
....

* Note that an element in React is not a component, but a component is comprised of multiple elements.
* Function components are very minimal in nature. Its only requirement is to return a React element.

[source, javascript]
----
// function component
function Hello(){
  return '<div>Hello</div>';
}

// class component
class HelloComponent extends React.Component{
  render(){
    return ( <div>Hello</div> );
  }
}
----

=== PropTypes

* React community provides a special package, `prop-types` to address the properties type mismatch problem.
* `prop-types` allows the properties of the component to be specified with type through a custom setting (propTypes) inside the component.

* Typescript : compile-time type checking
* prop-types : runtime type checking

[source, javascript]
----
import React from 'react';
import PropTypes from 'prop-types';

class FormattedMoney extends React.Component{

  constructor(props){
    super(props);

  }

  format(amount){
    return parseFloat(amount).toFixed(2);
  }

  render(){
    return(
      <span>{this.format(this.props.value)}</span>
    )
  }
}

FormattedMoney.PropTypes = {
  value: PropTypes.number.isRequired
}
----

* https://github.com/facebook/prop-types?tab=readme-ov-file#usage[PropTypes(`prop-types`) Usage]

[col="*", width=95%, role="ml-8", options="header, autowidth"]
|===
^| Type ^| Description ^| Examples ^| Remarks

| `PropTypes.array` |    |   | https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array[`Array`^]

| `PropTypes.bigint` | JavaScript `bigint` primitive  |
| https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt[`BigInt`^]

| `PropTypes.bool` | JavaScript `boolean` primitive |
| https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean[`Boolean`^]

| `PropTypes.func` |   |   | https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function[`Function`^]

| `PropTypes.number` | JavaScript `number` primitive  |
| https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number[`Number`^]

| `PropTypes.object` |   |   | https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object[`Object`^]

| `PropTypes.string` | JavaScript `string` primitive |
| https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String[`String`^]

| `PropTypes.symbol` | JavaScript `symbol` primitive |
| https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol[`Symbol`^]

| `PropTypes.node` | Anything that can be rendered |  |

| `PropTypes.element` | A React element |   |

| `PropTypes.elementType` | A React element type |   |

| `PropTypes.instanceOf(__clazz__)` | an instance of a class |   |

| `PropTypes.oneOf(__arr__)` | an enum
| `PropTypes.oneOf(['News', 'Photos'])` |

| `PropTypes.oneOfType(__arr__)` | could be one of many types
| `PropTypes.oneOfType([PropTypes.string, PropTypes.number, PropTypes.instanceOf(Message)])` |

| `PropTypes.arrayOf(__type__)` | An array of a certain type
| `PropTypes.arrayOf(PropTypes.number)`  |

| `PropsType.objectOf(__type__)` |   |   |

| `PropTypes.shape(__obj__)` | An object taking on a particular shape |   |

| `PropTypes.exact(__obj__)` | An object with warnings on extra properties |   |

| `PropTypes.any` | A value of any data type |   |
|===

* https://hygraph.com/blog/react-proptypes[*How to use PropTypes in React*^]


=== State

* The internal data represents the state of a React component and can be accessed using `this.state` member variable of the component.
* Whenever the state of the component is changed, the component will re-render itself by calling the `render()` method along with the new state. (reactive)
* React components have a [.underline]**built-in state object**. The state object is used to store all the property values that belong to the component in which this state is defined.

* React provides a [.underline]**single** API to maintain state in the component. The API is **`this.setState()`**. It accepts either a JavaScript object or a function that returns a JavaScript object.

* React **recommends** to use setState API with [.underline]**function** as it works correctly [.underline]##in async environment##. Instead of lambda function, normal JavaScript function can be used as well.

* A special feature of React state API is that it will be [.underline]**merged** with the existing state instead of replacing the state.

[source, typescript]
----
  this.setState( (state, props) =>
      ... function returning JavaScript object ...);

  this.setState( function(state, props) {
      return ... JavaScript object ...
  }
----

[source, typescript]
----
  setState<K extends keyof S>(
              state: ((prevState: Readonly<S>, props: Readonly<P>) => Pick<S, K> | S | null) | (Pick<S, K> | S | null),
              callback?: () => void,
          ): void;
----

=== Constructor

* In React, `constructor` is used for **state initialization** and **event binding** purposes as well.

* Initialization of props
* Initialization of the state
** Using `this.state = obj`
** Using `this.state.*`
** Using `this.setState()`


=== Component Lifecycle

[cols="*", width=95%, options="header,autowidth", role="ml-8"]
|===
^| Stage ^| Event Handler ^| Description ^| Remarks

.4+| Mounting | `constructor()`
| Invoked during the initial construction phase of the React component. Used to set initial **state** and **properties** of the component. |

| `getDerivedStateFromProps()` |   |

| `render()`
| Invoked after the construction of the component is completed. It renders the component in the virtual DOM instance. |

| `componentDidMount()`
| Invoked after the initial mounting of the component in the DOM tree. It is the good place to call API endpoints and to do network requests. |

.5+| Updating | `shouldComponentUpdate(__nextProps__, __nextState__)`
| Invoked during the update phase. Used to specify whether the component should update or not. |

| `getDerivedStateFromProps(__props__, __state__)`
| Invoked during both initial and update phase and just before the render() method. It returns the new state object. It is rarely used where the changes in properties results in state change. |

| `render()` |   |

| `getSnapshotBeforeUpdate(__prevProps__, __prevState__)`
| Invoked just before the rendered content is committed to DOM tree. It is mainly used to get some information about the new content. |

| `componentDidUpdate(__prevProps__, __prevState__, __snapshot__)`
| Network request can be done during this phase but only when there is difference in component's current and previous properties. |

| Unmounting
| `componentWillUnmount()`
| Invoked after the component is unmounted from the DOM. This is the good place to clean up the object. |
|===


=== Event Handler

* Typical Sample
.. Add a button with an onClick event
.. Set ``this.changeMessageHandler`` method as onClick event handler
.. Bind the event handler, `this.changeMessageHandler` in the constructor
.. Added the event handler and updated the state using `this.setState`.


* https://www.freecodecamp.org/news/this-is-why-we-need-to-bind-event-handlers-in-class-components-in-react-f7ea1a6f93eb/[**This is why we need to bind event handlers in Class Components in React**^]
** __In Class Components in React, when we pass the event handler function reference as a callback, the event handler method **loses its implicitly bound context**. When the event occurs and the handler is invoked, the `this` value **falls back to default binding** and is set to `undefined` , as class declarations and prototype methods run in strict mode.__
** __When we bind the `this` of the event handler to the component instance in the constructor, we can **pass it as a callback** without worrying about it losing its context.__


=== Event

* https://17.reactjs.org/docs/events.html[React v17 SyntheticEvent]

* Event Types
** Mouse Events
** Keyboard Events
** Focus Events

* Synthetic Event
** a simple cross-browser wrapper for native event instances making the events work identically across all browsers.

[cols="*", options="header, autowidth", role="ml-8"]
|===
^| Event ^| Callbacks ^| Properties ^| Remarks

| `ClipboardEvent` | `onCopy`, `onCut`, `onPaste` |   |

| `CompositionEvent` | `onCompositionStart`, `onCompositionEnd`, `onCompositionUpdate` | `string data` |

| `KeyboardEvent` | `onKeyPress`, `onKeyDown`, `onKeyUp` |   |

| `FocusEvent` | `onFocus`, `onBlur` |   |

|===

// https://mermaid.js.org/syntax/classDiagram.html
[mermaid,synthetic-event.svg]
....
classDiagram
  class SyntheticEvent{
    boolean bubbles
  }

....

=== Typescript

* An empty interface, ``{}`` and ``Object`` all represent "any non-nullish value"—not "an empty object" as you might think. Using these types is a common source of misunderstanding and is not recommended.

==== Types

[cols="*", width=95%, options="header, autowidth", role="ml-8"]
|===
^| Type ^| Description ^| Remarks

| `React.Component<__PropsType__, __StateType__>` |   |
| `React.SyntheticEvent` |   |
| `React.MouseEvent` |   |
| `React.KeyboardEvent` |    |

|===

==== React v17 Types

* https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/v17/index.d.ts

[%nowrap, typescript, role="!text-nowrap !whitespace-nowrap !ml-4"]
----

class Component<P, S>{
  ...
}

class PureComponent<P = {}, S = {}, SS = any> extends Component<P, S, SS> {}

interface FunctionComponent<P = {}> {
  ...
}

interface ComponentLifecycle<P, S, SS = any> extends NewLifecycle<P, S, SS>, DeprecatedLifecycle<P, S> {
  ...
}

interface BaseSyntheticEvent<E = object, C = any, T = any>{
  ...
}

interface SyntheticEvent<T = Element, E = Event> extends BaseSyntheticEvent<E, EventTarget & T, EventTarget>{}

interface ClipboardEvent<T = Element> extends SyntheticEvent<T, NativeClipboardEvent>{
  ...
}
----


=== Misc

* React toolchain will pre-process the css files ending with .module.css through CSS Module. Otherwise, it will be considered as a normal stylesheet.
* In short, the Props passed to a component are Read-Only.
* The concept of state allows React components to change their result as a response to changing user actions, network responses, etc. without violating this rule.


== References

=== JavaScript

==== `setInterval(), setTimeout()`
* https://developer.mozilla.org/en-US/docs/Web/API/Window/setInterval[`setInterval(_func_, _delay_[, _arg1_, _arg2_, ..., _argN_\])`^]
** Repeatedly calls a function or executes a code snippet, with a fixed time delay between each call.
** Returns a positive integer (typically within the range of 1 to 2,147,483,647) that uniquely identifies the interval timer created by the call

* https://developer.mozilla.org/en-US/docs/Web/API/Window/clearInterval[`clearInterval(_intervalID_)`^]
** Cancels a timed, repeating action which was previously established by a call to `setInterval()`.

* https://developer.mozilla.org/en-US/docs/Web/API/Window/setTimeout[`setTimeout(_func_, _delay_[, _arg1_, _arg2_, ..., _argN_\])`^]
** Sets a timer which executes a function or specified piece of code once the timer expires.
** Returns a positive integer (typically within the range of 1 to 2,147,483,647) that uniquely identifies the timer created by the call.

* https://developer.mozilla.org/en-US/docs/Web/API/Window/clearTimeout[`clearTimeout(_timeoutID_)`^]
** Cancels a timeout previously established by calling `setTimeout()`.

==== `Function.prototype.bind()`

* The most common use of `bind()` is to make a function that, no matter how it is called, is called with a particular `this` value.

* https://www.freecodecamp.org/news/this-is-why-we-need-to-bind-event-handlers-in-class-components-in-react-f7ea1a6f93eb/[This is why we need to bind event handlers in Class Components in React^] (May 4, 2018)
** We can figure out that when we call `setTimeout`, JavaScript internally assigns `obj.display` to its argument `callback`. This assignment operation, as we have seen before, causes the `display()` function to lose its context. To avoid this, we can explicitly hard bind the this value to a function by using the `bind()` method.

* https://www.freecodecamp.org/news/the-complete-guide-to-this-in-javascript/[The Complete Guide to this in JavaScript^] (January 18, 2020)

==== Misc

* Modules have been introduced in ECMAScript 2015.
* Modules are implicitly in strict mode.


=== Typescript

* https://www.typescriptlang.org/docs/handbook/react.html[React - Typescript Documentation^]
* https://react-typescript-cheatsheet.netlify.app/docs/basic/setup[React TypeScript Cheatsheet^]


== API

[.ml-8, cols="*", options="header,autowidth"]
|===
^| Class or ^| Description ^| Members ^| Remarks

| https://legacy.reactjs.org/docs/react-api.html[`React`^]
| the entry point to the React library
|   | global

| https://legacy.reactjs.org/docs/react-component.html[`React.Component`^]
|   | `render()`, `constructor(__props__)` |

| https://legacy.reactjs.org/docs/react-dom.html[`ReactDOM`]
|   |   |
|===

[source, typescript]
----
// https://legacy.reactjs.org/docs/react-component.html
class React.Component{

  // the props that were defined by the caller of this component.
  props: {};

  // data specific to this component that may change over time.
  state: {};

  // set the default props for the class.
  defaultProps: {};

  constructor(props);

  static getDerivedStateFromProps(props, state);

  render();

  componentDidMount();

  shouldComponentUpdate(nextProps, nextState);

  getSnapshotBeforeUpdate(prevProps, prevState);

  componentDidUpdate(prevProps, prevState, snapshot);

  componentWillUnmount();

  // This is the primary method you use to update the user interface in response to event handlers and server responses.
  setState(updater: (state, props) => state[, callback]);
}

----

=== Packages

[cols="*", options="header,autowidth", role="ml-8"]
|===
^| Package ^| Description ^| Elements ^| Remarks

| https://www.npmjs.com/package/react[`react`^]
| a JavaScript library for creating user interfaces.
|   | facebook

| https://www.npmjs.com/package/react-dom[`react-dom`^]
| the entry point to the DOM and server renderers for React.
|   | facebook

| https://github.com/facebook/prop-types[`prop-types`^]
| Runtime type checking for React props and similar objects.
|   | facebook, MIT

| https://www.npmjs.com/package/react-error-boundary[`react-error-boundary`^]
| Reusable React error boundary component. |   |

| https://www.npmjs.com/package/@types/react[`@types/react`^]
| type definitions for react |   |

| https://www.npmjs.com/package/@types/react-dom[`@types/react-dom`^]
| type definitions for react-dom |   |

| https://www.npmjs.com/package/@types/prop-types[`@types/prop-types`^]
| type definitions for prop-types |   |

|===


== Libraries

[cols="*", width=95%, options="header, autowidth", role="ml-8"]
|===

^| Library ^| License ^| Description ^| Remarks

| https://mui.com/[Material UI^] | Community: MIT, Pro/Premium: Commercial
| a comprehensive library of React components that features our independent implementation of Google's Material Design system. |

| https://react-bootstrap.github.io/[React Bootstrap^] | MIT
| Bootstrap 5 components built with React. |

| https://ant.design/[Ant Design^] | MIT
| An enterprise-class UI design language and React UI library. |

| https://ui.shadcn.com/[shadcn/ui^] | MIT
| a set of beautifully-designed, accessible components and a code distribution platform.
| headless UI

| https://headlessui.com/[Headless UI^] | MIT
| A set of completely unstyled, fully accessible UI components, designed to integrate beautifully with Tailwind CSS. | headless UI, Tailwind CSS

|===

* https://www.syncfusion.com/blogs/post/top-react-component-libraries[Top 10 React Component Libraries Every Developer Should Know] (Dec 10, 2024)
* https://www.robinwieruch.de/react-libraries/[React Libraries for 2025^] (February 17, 2025)


== Guides

* https://wormwlrm.github.io/2021/11/07/Rollup-React-TypeScript.html[Rollup 기반 라이브러리 개발 환경 구성하기^]
* https://suzzeong.tistory.com/115[날짜 라이브러리 비교(Day.js, Moment.js, date-fns, Luxon)^]

* https://bobbyhadz.com/blog/react-property-does-not-exist-on-type-readonly[React: Property 'X' does not exist on type 'Readonly<{}>'^] (Jan 15, 2023)

* https://github.com/tailwindlabs/tailwindcss/discussions/5258[Unknown at rule @apply css(unknownAtRules)^]
